apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-gateway
  namespace: taskflow-backend
spec:
  podSelector: {} # Applies to all pods 
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: taskflow-frontend
      podSelector:
        matchLabels:
          app: api-gateway